#!/usr/bin/env python3
"""Source of truth for the broom LED tube -> group -> Angio/port -> universe map.

Run this to (re)generate three artifacts next to it:
  - tube-map.json  machine-readable map (consumed by the control software)
  - tube-map.md    human doc + install/test checklist
  - tube-map.png   physical layout diagram

Change the knobs at the top and re-run; everything downstream stays in sync.
"""

import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

# ---- knobs -----------------------------------------------------------------
TUBES_PER_GROUP = 4          # one Angio port = one data line = one group
PIX_PER_TUBE = 40            # 16 px/m * 2.5 m
CHAN_PER_PIX = 3             # RGB
HERE = Path(__file__).parent

# Physical walk of the open-front U, front-left -> back -> front-right.
# Each Angio covers a contiguous run. (name, physical label, prefix, first, last)
ANGIOS = [
    ("A1", "Left-Front",  "L",  1, 28),
    ("A2", "Left-Back",   "L", 29, 56),
    ("A3", "Back",        "B",  1, 24),
    ("A4", "Right-Back",  "R",  1, 28),
    ("A5", "Right-Front", "R", 29, 56),
]

ANGIO_COLORS = {
    "A1": "#E63946", "A2": "#F4A261", "A3": "#2A9D8F",
    "A4": "#457B9D", "A5": "#9D4EDD",
}


# ---- build the map ---------------------------------------------------------
def build():
    groups = []
    gnum = 0
    for aname, aloc, prefix, first, last in ANGIOS:
        tubes = list(range(first, last + 1))
        port = 0
        for i in range(0, len(tubes), TUBES_PER_GROUP):
            gnum += 1
            port += 1
            chunk = tubes[i:i + TUBES_PER_GROUP]
            labels = [f"{prefix}{n:02d}" for n in chunk]
            groups.append({
                "group": gnum,
                "angio": aname,
                "angio_location": aloc,
                "port": port,
                "tubes": labels,
                "tube_count": len(chunk),
                "pixels": len(chunk) * PIX_PER_TUBE,
                "universe": gnum,
                "channels": len(chunk) * PIX_PER_TUBE * CHAN_PER_PIX,
            })
    return {
        "meta": {
            "tubes_per_group": TUBES_PER_GROUP,
            "pixels_per_tube": PIX_PER_TUBE,
            "channels_per_pixel": CHAN_PER_PIX,
            "total_tubes": sum(g["tube_count"] for g in groups),
            "total_groups": len(groups),
            "chip": "SM16703",
            "protocol": "sACN / E1.31",
            "color_order": "RGB",
        },
        "angios": [
            {"name": a[0], "location": a[1],
             "groups": [g["group"] for g in groups if g["angio"] == a[0]],
             "ports_used": len([g for g in groups if g["angio"] == a[0]]),
             "tube_count": sum(g["tube_count"] for g in groups if g["angio"] == a[0])}
            for a in ANGIOS
        ],
        "groups": groups,
    }


# ---- markdown doc + checklist ----------------------------------------------
def write_md(data):
    m = data["meta"]
    lines = []
    lines.append("# Broom LED tube map — groups, Angios, ports, universes")
    lines.append("")
    lines.append("> **Generated by [tube_map.py](tube_map.py) — do not hand-edit.** "
                 "Change the knobs in that script and re-run.")
    lines.append("")
    lines.append(f"**{m['total_tubes']} tubes** in **{m['total_groups']} groups** "
                 f"of {m['tubes_per_group']} across **5 Angio-8s**. "
                 f"One group = one data line = one Angio port = one sACN universe "
                 f"({m['tubes_per_group']}×{m['pixels_per_tube']} = "
                 f"{m['tubes_per_group']*m['pixels_per_tube']} px = "
                 f"{m['tubes_per_group']*m['pixels_per_tube']*m['channels_per_pixel']} "
                 f"ch ≤ 512).")
    lines.append("")
    lines.append(f"Chip **{m['chip']}**, color order **{m['color_order']}**, "
                 f"transport **{m['protocol']}**.")
    lines.append("")

    lines.append("## Angio placement (walking the open-front U)")
    lines.append("")
    lines.append("Tubes numbered around the U from **front-left → back → "
                 "front-right**: left `L01`(front)→`L56`(back), "
                 "back `B01`(left)→`B24`(right), "
                 "right `R01`(back)→`R56`(front).")
    lines.append("")
    lines.append("| Angio | Location | Tubes | Groups | Ports used | Spare ports |")
    lines.append("| --- | --- | --- | --- | ---: | ---: |")
    for a in data["angios"]:
        gs = a["groups"]
        span = f"G{gs[0]}–G{gs[-1]}"
        lines.append(f"| {a['name']} | {a['location']} | {a['tube_count']} | "
                     f"{span} | {a['ports_used']} | {8 - a['ports_used']} |")
    lines.append("")

    lines.append("## Full group map")
    lines.append("")
    lines.append("| Group | Angio | Port | Tubes | Px | Universe |")
    lines.append("| ---: | --- | ---: | --- | ---: | ---: |")
    for g in data["groups"]:
        tr = f"`{g['tubes'][0]}`–`{g['tubes'][-1]}`"
        lines.append(f"| **G{g['group']}** | {g['angio']} | {g['port']} | {tr} | "
                     f"{g['pixels']} | {g['universe']} |")
    lines.append("")

    lines.append("## Labeling scheme")
    lines.append("")
    lines.append("Label every tube at **both ends** with its tube ID and its group. "
                 "Example flag on a tube: `L05 / G2` = tube L05, group 2. "
                 "Within a group the data chain runs **serpentine**: the tube nearest "
                 "the Angio is the DIN head; flip alternate tubes so DOUT→DIN hops "
                 "stay short, then reverse those strands in software.")
    lines.append("")
    lines.append("```")
    lines.append("Angio port ─[330–470Ω]─▶ DIN[tube a] ─DOUT─▶ DIN[tube b] ─▶ "
                 "DIN[tube c] ─▶ DIN[tube d]   (one group)")
    lines.append("```")
    lines.append("")

    lines.append("## Install + test sequence")
    lines.append("")
    lines.append("Do it **one group at a time**. Recommended order below finishes one "
                 "Angio before moving to the next, so each controller + its network "
                 "config is validated end-to-end. **Start with G15 (Back Angio A3)** "
                 "as the very first group — it doubles as the open "
                 "*bench-test-SM16703-on-Angio-8* check.")
    lines.append("")
    lines.append("For each group: hang the 4 tubes → chain data (serpentine) "
                 "→ tap +24 V + shared GND → label both ends → ping me "
                 "to light it from software → confirm all 4 tubes + color order "
                 "→ check the box.")
    lines.append("")
    for a in data["angios"]:
        lines.append(f"### {a['name']} — {a['location']} "
                     f"({a['tube_count']} tubes)")
        for g in [g for g in data["groups"] if g["angio"] == a["name"]]:
            tr = f"{g['tubes'][0]}–{g['tubes'][-1]}"
            lines.append(f"- [ ] **G{g['group']}** · port {g['port']} · "
                         f"tubes {tr} · universe {g['universe']}")
        lines.append("")

    lines.append("## Diagram")
    lines.append("")
    lines.append("![Tube layout](tube-map.png)")
    lines.append("")
    lines.append("## Related")
    lines.append("")
    lines.append("- [controllers.md](controllers.md) — data wiring, "
                 "shared-ground, serpentine reverse")
    lines.append("- [led-tubes.md](led-tubes.md) — SM16703 electricals "
                 "(16 px/m, 5 V data, RGB, series resistor)")
    lines.append("- [../electrical/led-wiring.md](../electrical/led-wiring.md) "
                 "— power injection (separate from data)")
    lines.append("- [tube-map.json](tube-map.json) — machine-readable map "
                 "for the control software")
    lines.append("")
    (HERE / "tube-map.md").write_text("\n".join(lines))


# ---- diagram ---------------------------------------------------------------
def _font(size, bold=False):
    names = (["DejaVuSans-Bold.ttf", "Arial Bold.ttf"] if bold
             else ["DejaVuSans.ttf", "Arial.ttf"])
    for n in names:
        try:
            return ImageFont.truetype(n, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _cell(draw, x, y, w, h, color, gnum, trange, port):
    draw.rounded_rectangle([x, y, x + w, y + h], radius=6, fill=color)
    f_big = _font(20, bold=True)
    f_sm = _font(13)
    draw.text((x + w / 2, y + 10), f"G{gnum}", font=f_big, fill="white",
              anchor="mt")
    draw.text((x + w / 2, y + h - 26), trange, font=f_sm, fill="white",
              anchor="mt")
    draw.text((x + w / 2, y + h - 11), f"p{port}", font=f_sm, fill="#ffffffcc",
              anchor="mt")


def write_png(data):
    W = 1500
    cw, ch, gap = 150, 74, 10
    by = data["groups"]
    left = [g for g in by if g["angio"] in ("A1", "A2")]
    back = [g for g in by if g["angio"] == "A3"]
    right = [g for g in by if g["angio"] in ("A4", "A5")]

    top = 110
    col_rows = max(len(left), len(right))
    col_bottom = top + col_rows * (ch + gap)
    back_y = col_bottom + 20
    legend_y = back_y + ch + 44
    H = int(legend_y + 70)

    img = Image.new("RGB", (W, H), "#0d1b2a")
    d = ImageDraw.Draw(img)
    d.text((W / 2, 24), "Glorb broom — LED tube groups (open-front U)",
           font=_font(30, bold=True), fill="white", anchor="mt")
    d.text((W / 2, 62), "front-left OPEN (driver sightline)  ·  "
           "front is the TOP edge", font=_font(16), fill="#a9c0d6", anchor="mt")
    col_x_left = 120
    col_x_right = W - 120 - cw

    # left column: front (top) -> back (bottom)
    for i, g in enumerate(left):
        y = top + i * (ch + gap)
        _cell(d, col_x_left, y, cw, ch, ANGIO_COLORS[g["angio"]],
              g["group"], f"{g['tubes'][0]}–{g['tubes'][-1]}", g["port"])

    # right column: front (top) -> back (bottom): reverse so back is at bottom
    for i, g in enumerate(reversed(right)):
        y = top + i * (ch + gap)
        _cell(d, col_x_right, y, cw, ch, ANGIO_COLORS[g["angio"]],
              g["group"], f"{g['tubes'][0]}–{g['tubes'][-1]}", g["port"])

    # back row: left -> right, along the bottom
    n = len(back)
    total_w = n * cw + (n - 1) * gap
    start_x = (W - total_w) / 2
    for i, g in enumerate(back):
        x = start_x + i * (cw + gap)
        _cell(d, x, back_y, cw, ch, ANGIO_COLORS[g["angio"]],
              g["group"], f"{g['tubes'][0]}–{g['tubes'][-1]}", g["port"])

    # side labels
    d.text((col_x_left + cw / 2, top - 26), "LEFT (L01→L56)",
           font=_font(16, bold=True), fill="white", anchor="mt")
    d.text((col_x_right + cw / 2, top - 26), "RIGHT (R01→R56)",
           font=_font(16, bold=True), fill="white", anchor="mt")
    d.text((W / 2, back_y + ch + 8), "BACK (B01→B24)",
           font=_font(16, bold=True), fill="white", anchor="mt")

    # legend
    ly = legend_y
    d.text((60, ly), "Angios:", font=_font(16, bold=True), fill="white")
    lx = 150
    for a in data["angios"]:
        c = ANGIO_COLORS[a["name"]]
        d.rounded_rectangle([lx, ly - 2, lx + 22, ly + 18], radius=4, fill=c)
        d.text((lx + 30, ly), f"{a['name']} {a['location']}",
               font=_font(15), fill="white")
        lx += 240

    img.save(HERE / "tube-map.png")


def main():
    data = build()
    (HERE / "tube-map.json").write_text(json.dumps(data, indent=2))
    write_md(data)
    write_png(data)
    print(f"{data['meta']['total_tubes']} tubes, "
          f"{data['meta']['total_groups']} groups written.")


if __name__ == "__main__":
    main()
